server:
  port: 8000

eureka:
  client:
    register-with-eureka : false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: place-service
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/place-service/**
          filters:
            - RewritePath=/place-service/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}

token:
  secret: "2jdfK@39f#sdklfj!O@8asdj8D3jf*o@sdnfa9WE@Sd839sjdlfjSD83sjdfL"