server:
  port: 8000

eureka:
  client:
    register-with-eureka : false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
        - id: place-service
          uri: lb://PLACE-SERVICE
          predicates:
            - Path=/place-service/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**